name: Deploy with Retool

on:
  push:
    branches: [main] # Trigger the workflow on pushes to the main branch
    paths:
      - 'src/*' # Only self-deploy when the src folder has code changes

jobs:
  deploy:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu as the runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Checkout the repository's code
    
    - name: Use Node.js v20
      uses: actions/setup-node@v3 # Set up Node.js version 20.x
      with:
        node-version: 20.x
        
    - name: Install dependencies
      run: npm install # Install project dependencies using npm
      
    - name: Login to Retool
      run: |
        {
          echo ""; # Enter to proceed
          sleep 1; # Wait for a second
          echo "${{secrets.SUB_DOMAIN}}"; # Enter subdomain from secrets
          sleep 1; # Wait for a second
          echo "${{secrets.RETOOL_CUSTOM_COMPONENT_TOKEN}}"; # Enter token from secrets
          sleep 1; # Wait for a second
        } | npx retool-ccl login # Use the login command with entered information
        
    - name: Deploy to Retool
      run: npx retool-ccl deploy # Deploy to Retool using the retool-ccl command line tool
