name: Deploy with Retool

on:
  push:
    branches: [main] # Trigger the workflow on pushes to the main branch
    paths:
      - 'src/**/*' # Only self-deploy when the src folder has code changes

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Use Node.js v20
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        
    - name: Install dependencies
      run: |
        npm cache clean --force
        npm install
      
    - name: Login to Retool
      run: |
        {
          sleep 1;
          echo "";
          sleep 1;
          echo "${{secrets.RETOOL_SUB_DOMAIN}}";
          sleep 1;
          echo "${{secrets.RETOOL_CUSTOM_COMPONENT_TOKEN}}";
          sleep 1;
        } | npx retool-ccl login
        
    - name: Deploy to Retool
      run: npx retool-ccl deploy
